
data:
  dataset: HandWriting_TS
  data_dir: DATA/
  label_dir: Labels/
  pad_tr: 2048
  train_size: 75
  val_size: 15
  test_size: 10
  device: mps

RNN:
  training:
    name: RNN
    epochs: 30
    batch_size: 16
    learning_rate: 0.001
    optimizer: adam
    warmup_ratio: 0.1
    validation_split: 0.2
    num_workers: 10

  model:
    input_size: 16
    output_size: 3
    hidden_size: 2048
    num_layers: 2
    dropout: 0.2

LSTM:
  training:
    name: LSTM
    epochs: 30
    batch_size: 16
    learning_rate: 0.001
    optimizer: adam
    warmup_ratio: 0.1
    validation_split: 0.2
    num_workers: 10

  model:
    input_size: 16
    output_size: 3
    hidden_size: 2048
    num_layers: 2
    dropout: 0.2
    bidirectional: false

GRU:
  training:
    name: GRU
    epochs: 30
    batch_size: 16
    learning_rate: 0.001
    optimizer: adam
    warmup_ratio: 0.1
    validation_split: 0.2
    num_workers: 10


  model:
    input_size: 16
    output_size: 3
    hidden_size: 2048
    num_layers: 2
    dropout: 0.2
    bidirectional: false

